import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'
import { planStateValidator } from './lib/plans'
import {
  appRuleOverrides,
  dictationModeValidator,
  formattingPreferencesValidator,
  platformValidator,
  subscriptionValidator,
  syncPreferencesValidator,
  toneValidator
} from './lib/validators'

/**
 * Document-relational layout: one row per synced record, every table keyed by the owning user and
 * indexed for the lookups the clients perform. Users' own provider credentials are intentionally
 * absent; API keys for a bring-your-own model stay on the device that entered them. The instance's
 * managed-model credentials live in deployment environment variables, never in the database.
 */
export default defineSchema({
  users: defineTable({
    /** Clerk user id (`sub` claim of the session JWT). */
    clerkId: v.string(),
    email: v.optional(v.string()),
    name: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    /**
     * Where the account is in its lifecycle (see lib/plans.ts). Absent on rows created before the
     * trial existed; they read as `free` until `upsertUser` or the backfill grants their trial.
     */
    plan: v.optional(planStateValidator),
    /** End of the 14-day Pro trial, epoch ms. A scheduled `entitlements.endTrial` flips the state. */
    trialEndsAt: v.optional(v.number()),
    /** Stripe customer (`cus_…`) once the account has been through Checkout. */
    stripeCustomerId: v.optional(v.string()),
    /** Latest Stripe subscription snapshot; written only by the Stripe webhook. */
    subscription: v.optional(subscriptionValidator),
    /** Account-level onboarding. Device-level steps (microphone, shortcut) are repeated per device. */
    onboardingCompletedAt: v.optional(v.number()),
    onboardingVersion: v.optional(v.number()),
    /** Number of rows in historyEntries, maintained by history mutations so pruning never scans. */
    historyCount: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number()
  })
    .index('by_clerkId', ['clerkId'])
    .index('by_stripeCustomerId', ['stripeCustomerId']),

  /**
   * Managed inference consumed per account and calendar month (UTC). One row per (user, period);
   * the gateway checks it before forwarding a request and adds to it afterwards.
   */
  inferenceUsage: defineTable({
    userId: v.id('users'),
    /** `YYYY-MM` in UTC. */
    period: v.string(),
    sttSeconds: v.number(),
    sttRequests: v.number(),
    llmTokens: v.number(),
    llmRequests: v.number(),
    /** Start of the current request-rate window and the requests seen in it. */
    windowStart: v.optional(v.number()),
    windowCount: v.optional(v.number()),
    updatedAt: v.number()
  }).index('by_user_and_period', ['userId', 'period']),

  /**
   * Managed inference per account and UTC day, behind the rolling-week word cap and the daily
   * guardrails of the free tier. One row per (user, day); a week is at most seven reads.
   */
  inferenceDays: defineTable({
    userId: v.id('users'),
    /** `YYYY-MM-DD` in UTC. */
    day: v.string(),
    /** Words in the transcripts the speech model returned. */
    words: v.number(),
    sttSeconds: v.number(),
    /** Transcriptions. */
    dictations: v.number(),
    /** Formatting requests (chat completions and /v1/format). */
    formats: v.number(),
    updatedAt: v.number()
  }).index('by_user_and_day', ['userId', 'day']),

  devices: defineTable({
    userId: v.id('users'),
    /** Stable per-install identifier generated by the client. */
    deviceId: v.string(),
    name: v.string(),
    platform: platformValidator,
    appVersion: v.string(),
    lastSeenAt: v.number(),
    createdAt: v.number()
  })
    .index('by_user', ['userId'])
    .index('by_user_and_deviceId', ['userId', 'deviceId']),

  dictionaryEntries: defineTable({
    userId: v.id('users'),
    word: v.string(),
    /** Normalized (trimmed, lower-cased, single-spaced) word used for de-duplication. */
    wordKey: v.string(),
    aliases: v.array(v.string()),
    fuzzy: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number()
  })
    .index('by_user', ['userId'])
    .index('by_user_and_wordKey', ['userId', 'wordKey']),

  snippets: defineTable({
    userId: v.id('users'),
    trigger: v.string(),
    triggerKey: v.string(),
    content: v.string(),
    createdAt: v.number(),
    updatedAt: v.number()
  })
    .index('by_user', ['userId'])
    .index('by_user_and_triggerKey', ['userId', 'triggerKey']),

  appRules: defineTable({
    userId: v.id('users'),
    match: v.string(),
    matchKey: v.string(),
    tone: toneValidator,
    ...appRuleOverrides,
    createdAt: v.number(),
    updatedAt: v.number()
  })
    .index('by_user', ['userId'])
    .index('by_user_and_matchKey', ['userId', 'matchKey']),

  preferences: defineTable({
    userId: v.id('users'),
    formatting: v.optional(formattingPreferencesValidator),
    language: v.optional(v.string()),
    sync: v.optional(syncPreferencesValidator),
    updatedAt: v.number()
  }).index('by_user', ['userId']),

  stats: defineTable({
    userId: v.id('users'),
    totalWords: v.number(),
    totalSessions: v.number(),
    totalSpeechMs: v.number(),
    streakDays: v.number(),
    /** Local calendar day (YYYY-MM-DD) of the last session, as reported by the device. */
    lastSessionDay: v.string(),
    /** Recently counted session ids; lets a device replay `recordSession` without double counting. */
    recentSessionIds: v.optional(v.array(v.string())),
    updatedAt: v.number()
  }).index('by_user', ['userId']),

  historyEntries: defineTable({
    userId: v.id('users'),
    deviceId: v.string(),
    /** Client-generated id of the dictation session; makes pushes idempotent. */
    entryId: v.string(),
    createdAt: v.number(),
    mode: dictationModeValidator,
    rawText: v.optional(v.string()),
    finalText: v.string(),
    wordCount: v.number(),
    speechMs: v.number(),
    appName: v.optional(v.string()),
    provider: v.string(),
    model: v.string(),
    llmUsed: v.boolean()
  })
    .index('by_user_and_createdAt', ['userId', 'createdAt'])
    .index('by_user_and_entryId', ['userId', 'entryId'])
})
